{
 "title": "Rona Dash",
 "time": { "from": "2020-01-01T06:00:00.000Z", "to": "now+1w" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "select distinct \"Country\" from \"Records\""
   },
   {
    "name": "state",
    "label": "Province/State",
    "query": "select Distinct \"Province_State\" from \"Records\" where \"Country\" = '${country}'"
   },
   {
    "name": "county",
    "label": "County",
    "query": "select Distinct \"County\" from \"Records\" where \"Country\" = '${country}' and \"Province_State\" = '${state}'"
   }
  ]
 },
 "panels": [
  { "title": "County Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Selected Counties - Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"County\" AS metric,\n  \"Active\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state' AND\n  \"County\" in ($county)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Selected Counties - Deaths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"County\" AS metric,\n  \"Deaths\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state' AND\n  \"County\" in ($county)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Selected Counties - Confirmed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"County\" AS metric,\n  \"Confirmed\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state' AND\n  \"County\" in ($county)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Selected Counties - Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"County\" AS metric,\n  \"Recovered\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state' AND\n  \"County\" in ($county)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Selected Counties - All Metrics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"County\" AS metric,\n  \"Active\",\n  \"Confirmed\",\n  \"Deaths\",\n  \"Recovered\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state' AND\n  \"County\" in ($county)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Province/State Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$state - Active",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"Province_State\" AS metric,\n  sum(\"Active\") AS \"\"\"Active\"\"\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state'\nGROUP BY 1, \"Country\", \"Province_State\",2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$state - Deaths",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"Province_State\" AS metric,\n  sum(\"Deaths\") AS \"\"\"Deaths\"\"\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state'\nGROUP BY 1, \"Country\", \"Province_State\",2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$state - Confirmed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"Province_State\" AS metric,\n  sum(\"Confirmed\") AS \"\"\"Confirmed\"\"\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state'\nGROUP BY 1, \"Country\", \"Province_State\",2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$state - Recovered",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"Province_State\" AS metric,\n  sum(\"Recovered\") AS \"\"\"Recovered\"\"\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country' AND\n  \"Province_State\" = '$state'\nGROUP BY 1, \"Country\", \"Province_State\",2\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Country Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "$country - Active",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"Country\" AS metric,\n  sum(\"Active\") AS \"\"\"Active\"\"\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country'\nGROUP BY 1, \"Country\",2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$country - Deaths",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"Country\" AS metric,\n  sum(\"Deaths\") AS \"\"\"Deaths\"\"\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country'\nGROUP BY 1, \"Country\",2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$country - Confirmed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"Country\" AS metric,\n  sum(\"Confirmed\") AS \"\"\"Confirmed\"\"\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country'\nGROUP BY 1, \"Country\",2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$country - Recovered",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"Last_Update\",$__interval),\n  \"Country\" AS metric,\n  sum(\"Recovered\") AS \"\"\"Recovered\"\"\"\nFROM \"Records\"\nWHERE\n  $__timeFilter(\"Last_Update\") AND\n  \"Country\" = '$country'\nGROUP BY 1, \"Country\",2\nORDER BY 1,2"
      }
     ]
    }
   ]
  }
 ]
}